name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Semantic Version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        major_pattern: "major:"
        minor_patern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"      
      id: version

    - name: Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Iniciando login"
        echo "NUEVA VERSION $NEW_VERSION"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"

    # - name: Docker build image
    #   run: |
    #     docker build -t dayronlmao/docker-graphql:0.0.2 .

    # - name: Docker push image
    #   run: |
    #     docker push dayronlmao/docker-graphql:0.0.2
          
